name: Build and Test on Linux

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  proc_num: $(nproc)

# https://github.com/actions/runner-images
jobs:
  clang-unittest-asan:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-essential-dependencies
    - uses: ./.github/actions/init-ut-make-config
      with:
        options: --with-bthread-tracer --with-asan
    - name: compile tests
      run: |
        cat config.mk
        cd test
        make NEED_GPERFTOOLS=0 -j ${{env.proc_num}}
    - name: run tests
      run: |
        cd test
        sh ./run_tests.sh

  bazel-bvar-unittest:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: bazel test --verbose_failures //test:bvar_test
    - run: bazel test --verbose_failures --define with_babylon_counter=true //test:bvar_test
    - run: bazel test --verbose_failures --action_env=CC=clang //test:bvar_test
    - run: bazel test --verbose_failures --action_env=CC=clang --define with_babylon_counter=true //test:bvar_test
