name: Build and Test on Linux

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  proc_num: $(nproc)

# https://github.com/actions/runner-images
jobs:
  clang-unittest:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-essential-dependencies
    - uses: ./.github/actions/init-ut-make-config
      with:
        options: --cc=clang-12 --cxx=clang++-12 --with-bthread-tracer
    - name: compile tests
      run: |
        cat config.mk
        cd test
        make -j ${{env.proc_num}} bthread_unittest
    - name: run tests
      run: |
        cd test
        sh ./run_tests.sh
